name: flutter_device_imei
description: "A flutter plugin that provides consistent device unique identifier. "
version: 0.0.1
homepage: https://pranilshah.in/


environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: 2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.2

flutter:

  plugin:
    platforms:
      android:
        package: com.pranilshah.flutter_device_imei
        pluginClass: FlutterDeviceImeiPlugin
      ios:
        pluginClass: FlutterDeviceImeiPlugin

